version: '3.7'
services:
  app:
    image: cosmtrek/air
    working_dir: /app
    ports:
      - 9090:80
    volumes:
      - .:/app/
    networks:
      internal-network:
        aliases:
          - app.service

  rabbitmq:
    image: rabbitmq:3.9.13-alpine
    networks:
      internal-network:
        aliases:
          - rabbitmq.service

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      internal-network:
        aliases:
          - db.service

  cache:
    image: memcached:1.6-alpine
    networks:
      internal-network:
        aliases:
          - cache.service

networks:
  internal-network:
    name: internal-network
